# Generated by Django 5.2.17 on 2026-09-08 19:40

import shop.media
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="original",
            field=models.FileField(blank=True, editable=False, upload_to="originals/%Y/%m/"),
        ),
        migrations.AddField(
            model_name="productimage",
            name="renditions",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name="brand",
            name="image",
            field=shop.media.ProcessedImageField(blank=True, upload_to="editorial/"),
        ),
        migrations.AlterField(
            model_name="brand",
            name="logo",
            field=shop.media.ProcessedImageField(blank=True, upload_to="brands/"),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=shop.media.ProcessedImageField(blank=True, upload_to="editorial/"),
        ),
        migrations.AlterField(
            model_name="collection",
            name="image",
            field=shop.media.ProcessedImageField(blank=True, upload_to="editorial/"),
        ),
        migrations.AlterField(
            model_name="location",
            name="image",
            field=shop.media.ProcessedImageField(blank=True, upload_to="editorial/"),
        ),
        migrations.AlterField(
            model_name="pagesection",
            name="image",
            field=shop.media.ProcessedImageField(blank=True, upload_to="editorial/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=shop.media.ProcessedImageField(blank=True, upload_to="editorial/"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=shop.media.ProcessedImageField(
                height_field="height", upload_to="products/%Y/%m/", width_field="width"
            ),
        ),
        migrations.AlterField(
            model_name="release",
            name="image",
            field=shop.media.ProcessedImageField(blank=True, upload_to="editorial/"),
        ),
    ]
