export type Size = {
  id: number;
  size_id: number;
  label: string;
  system: string;
  sku: string;
  available: number;
};
export type Variant = {
  id: number;
  sku: string;
  color_name: string;
  color_code: string;
  color_family: string;
  price: string;
  compare_at_price: string | null;
  in_stock: boolean;
  is_default: boolean;
  image: string;
  hover_image: string;
  images: {
    id: number;
    url: string;
    alt: string;
    view_type: string;
    width: number;
    height: number;
    renditions?: { url: string; width: number; height: number }[];
  }[];
  sizes: Size[];
};
export type Product = {
  id: number;
  slug: string;
  name: string;
  subtitle: string;
  description: string;
  brand: { id: number; name: string; slug: string; logo: string };
  category: { id: number; name: string; slug: string };
  gender: string;
  age_group: string;
  sport: string;
  style: string;
  price: string;
  compare_at_price: string | null;
  rating: string | null;
  review_count: number;
  is_new: boolean;
  is_best_seller: boolean;
  is_limited: boolean;
  see_price_in_bag: boolean;
  badges: string[];
  default_variant_id: number;
  max_card_swatches: number;
  fit: string;
  width: string;
  details: string[];
  variants: Variant[];
  seo_title: string;
  seo_description: string;
};
export type Page<T> = { count: number; next: string | null; previous: string | null; results: T[] };
export type Directory = {
  id: number;
  name: string;
  slug: string;
  description: string;
  image: string;
};
export type Navigation = { label: string; href: string; children: Navigation[] };
export type Section = {
  id: number;
  type: string;
  title: string;
  subtitle: string;
  body: string;
  image: string;
  href: string;
  cta: string;
  settings: unknown;
  products: Product[];
};
export type Site = {
  name: string;
  tagline: string;
  currency: string;
  announcements: { id: number; text: string; href: string }[];
  navigation: Navigation[];
  sections: Section[];
  flags: Record<string, boolean>;
  payment_enabled: boolean;
  test_payments: boolean;
  demo: boolean;
  footer: { slug: string; title: string }[];
};
export type CartItem = {
  id: number;
  quantity: number;
  variant_size_id: number;
  product_slug: string;
  product_name: string;
  brand: string;
  color_name: string;
  size_label: string;
  image: string;
  unit_price: string;
  line_total: string;
  available: number;
};
export type Cart = {
  id: string;
  items: CartItem[];
  subtotal: string;
  discount: string;
  shipping: string;
  total: string;
  currency: string;
  promo_code: string;
  free_shipping_remaining: string;
};
export type User = { id: number; email: string; first_name: string };
export type Order = {
  reference: string;
  status: string;
  email: string;
  created_at: string;
  items: CartItem[];
  subtotal: string;
  discount: string;
  shipping: string;
  total: string;
  currency: string;
  address: Record<string, string>;
  history: { status: string; note: string; created_at: string }[];
  tracking_token?: string;
};
export type Release = Directory & {
  title: string;
  release_at: string;
  status: string;
  product: Product | null;
  server_time: string;
};
export type Facets = {
  brands: { slug: string; name: string; count: number }[];
  categories: { slug: string; name: string; count: number }[];
  sizes: { id: number; label: string; system: string; count: number }[];
  colors: { name: string; code: string; count: number }[];
  genders: { value: string; label: string; count: number }[];
  price: { min: string; max: string };
};
